image: gradle:8.4.0-jdk17-alpine
stages:
  - build
  - test
variables:
  GIT_SSL_NO_VERIFY: "true"
before_script:
  - echo "Start Automated Build"
  - |
    if [ "$CI_RUNNER_TAGS" = "docker-grupo11" ]; then
      export GRADLE_USER_HOME=$(pwd)/.gradle
      chmod +x ./gradlew
    fi
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
build:
  stage: build
  script:
    - if [ "$CI_RUNNER_TAGS" = "docker-grupo11" ]; then ./gradlew assemble; fi
  tags:
    - docker-grupo11
  artifacts:
    paths:
      - build/libs/*.jar
test_black_box:
  stage: test
  tags:
    - docker-grupo11
  script:
    - if [ "$CI_RUNNER_TAGS" = "docker-grupo11" ]; then ./gradlew test; fi
  artifacts:
    paths:
      - build/test-results/test/TEST-*.xml
  needs: [build]
test_white_box:
  stage: test
  tags:
    - docker-grupo11
  script:
    - if [ "$CI_RUNNER_TAGS" = "docker-grupo11" ]; then ./gradlew jacocoTestReport; fi
  artifacts:
    paths:
      - build/reports/jacoco*
  needs: [build]
after_script:
  - echo "End Automated Build"