image: gradle:8.4.0-jdk17-alpine
stages:
  - build
  - test 
variables:  
  GIT_SSL_NO_VERIFY: "true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"
before_script:
  - echo "Start Automated Build"
  - export GRADLE_USER_HOME='pwd'/.gradle
  - chmod +x ./gradlew 
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
build:
    stage: build
    script:
        - ./gradlew assemble
    tags:
      - docker-runner
    artifacts:
        paths:
        - build/libs/*.jar
test_black_box:
    stage: test
    tags:
      - docker-runner
    script:
        - ./gradlew test
    artifacts:
        paths:
          - build/test-results/test/TEST-*.xml
    needs: [build]
test_white_box:
  stage: test
  tags:
    - docker-runner
  script:
    - ./gradlew jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco*
  needs: [build]

checkstyle:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -Pcicdprofile checkstyle:check'

# PMD code quality analysis.
pmd:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -Pcicdprofile pmd:check'

# SpotBugs code quality analysis.
spotbugs:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -Pcicdprofile spotbugs:check'

# Test code coverage analysis.
code-coverage:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -P-Pcicdprofile install'

after_script:
  - echo "End Automated Build"