image: gradle:8.4.0-jdk17-alpine
stages:
  - build
  - test
variables:
  GIT_SSL_NO_VERIFY: "true"
before_script:
  - echo "Start Automated Build"
  - |
    if ($env:CI_RUNNER_TAGS -eq "docker-grupo11") {
      $env:GRADLE_USER_HOME = "$(Get-Location)/.gradle"
      chmod +x ./gradlew
    }
cache:
  paths:
    - "%CD%/.gradle/wrapper"
    - "%CD%/.gradle/caches"
build:
  stage: build
  script:
    - if ($env:CI_RUNNER_TAGS -eq "docker-grupo11") { ./gradlew assemble }
  tags:
    - docker-grupo11
  artifacts:
    paths:
      - build/libs/*.jar
test_black_box:
  stage: test
  tags:
    - docker-grupo11
  script:
    - if ($env:CI_RUNNER_TAGS -eq "docker-grupo11") { ./gradlew test }
  artifacts:
    paths:
      - build/test-results/test/TEST-*.xml
  needs: [build]
test_white_box:
  stage: test
  tags:
    - docker-grupo11
  script:
    - if ($env:CI_RUNNER_TAGS -eq "docker-grupo11") { ./gradlew jacocoTestReport }
  artifacts:
    paths:
      - build/reports/jacoco*
  needs: [build]
after_script:
  - echo "End Automated Build"